name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ftp_details
    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install Node dependencies
      - name: Install NPM Dependencies
        run: npm install

      # 4. Build frontend assets (Vite → public/build)
      - name: Build Assets
        run: npm run build

      # Create .env file
      - name: Setup .env
        run: |
          if [ -f .env.example ]; then
            echo "Copying .env.example to .env"
            cp .env.example .env
          else
            echo ".env.example not found, creating basic .env"
            cat <<EOF > .env
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=http://localhost

          LOG_CHANNEL=stack
          LOG_LEVEL=error

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=laravel
          DB_USERNAME=root
          DB_PASSWORD=

          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          EOF
              fi

      #5. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      # 6. Install Composer dependencies - ( don't use it if your ftp server is very slow )
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # 7. Deploy via FTP
      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            vendor/**
            .git/**
            .github/**
            node_modules/**
            tests/**
            storage/**
            public/storage/**
            .env
            resources/js/**
            resources/css/**
            vite.config.js
            package.json
            package-lock.json
