name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ftp_details
    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install Node dependencies
      - name: Install NPM Dependencies
        run: npm install

      # 4. Build frontend assets (Vite → public/build)
      - name: Build Assets
        run: npm run build


      #5. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      # 6. Install Composer dependencies - ( don't use it if your ftp server is very slow )
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # 7. Deploy via FTP
      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            vendor/**
            .git/**
            .github/**
            node_modules/**
            tests/**
            storage/**
            public/storage/**
            .env
            resources/js/**
            resources/css/**
            vite.config.js
            package.json
            package-lock.json
